### ISSUE TITLE
custom trigger key not saved

### ISSUE THREAD

**Issue by Cammagno** [JulesGuesnon/obsidian-markdown-shortcuts#1]
I've tried to customize the trigger key, but the ones I've inserted are not saved, and after trying also the default one disappears

**Comment by JulesGuesnon** [comment]
Hello @Cammagno !

I tried to reproduce the issue but I couldn't. 
On which version are you? (you can get it into the `Community plugins > Installed plugin` list) 
Do you have any idea of the steps to reproduce the error?

**Comment by Cammagno** [comment]
> On which version are you?

I'm on 0.2.2
Here a gif with me trying to change the trigger character (from < to >)  without success: it keeps the default one

![MarkdownCommand bug](https://user-images.githubusercontent.com/95725064/153934528-029ef727-562c-4063-bb57-8bdb5e63b248.gif)

**Comment by JulesGuesnon** [comment]
Thanks a lot for the gif, it helped me to figure out the issue. 
Try with `0.2.3` it should be fixed now

**Comment by Cammagno** [comment]
> Try with `0.2.3` it should be fixed now

Yes, it's fixed now. Thanks! :)
