### ISSUE TITLE
upload to official store so it would be easy to install ?

### ISSUE THREAD

**Issue by makerjackie** [JulesGuesnon/obsidian-markdown-shortcuts#2]

**Comment by JulesGuesnon** [comment]
Hello @Jackiexiao,

The plugin is actually available in the store: 

![image](https://user-images.githubusercontent.com/36401048/171999711-b744b6b1-e975-4254-98e6-c0c930095b5b.png)

Is it just unclear as it's not mentioned into the documentation?

**Comment by makerjackie** [comment]
oh! this plugin is in the end of search result, I miss it .... ok.... thx!
![image](https://user-images.githubusercontent.com/18050469/172000048-65da8a01-b854-49ac-8e46-19d27da549d3.png)
